equations:
  one:   "q1*(2*a^2*tau*q2 - mu*(q1-q2)*q1*r)"
  two:   "(q1 - q2)*r*(q1^2 - a^2)"
  three: "tau*q2*r*(q1^2 - a^2)"

glob_left: -20
glob_right: 1000
solver:
  meth: "RK45" #"rosenbrock"
  minstep: 1e-8
# stiffness: true # этот параметр убираю, если используется rkf45, ck45, rosenbrock, classical
eps1: 1e-6 # отступ от последней успешно рассчитанной точки по параметру t
eps2: 1e-6 # отступ от последней успешно рассчитанной точки по параметру t
# значения параметров zero infty для "общего" анализа
# zero: 1e-6 # параметр для искусственного определения окрестности нуля
# infty: 1e+5  # параметр для обозначения события, когда следует остановить решение
# значения параметров zero infty для анализа окрестности точки (0,0)
zero: 1e-6 # параметр для искусственного определения окрестности нуля
infty: 1e+3  # параметр для обозначения события, когда следует остановить решение
eps_w: 0.01 # "радиус" сферы в условии близости конечной точки траектории к линии особых точек q1,q2,r=(a,q2,2*a*tau*q2/mu/(a-q2))
delta_blue: 0.01 # в признаке синих конечная точка по q1 должна быть меньше начальной в delta раз
abserr: "none"
relerr: "none"

# набор параметров для построения глобальной картины u, v, R = [0.01..100, 0.01..100, 0.001..1000]
const:
  mu: 16 # 4 - "опорное" значение параметра
  tau: 1
  a: 1
n_u: 501
n_v: 501
n_r: 3
L_u0: -3
L_u1: 2
L_v0: -5
L_v1: 0
L_r0: -5
L_r1: -4
logr: 1
logu: 1
logv: 1
logall: 0
eps_u: 1.0e-4
eps_r: 0.0001

saveto: './res'

cross: 'yes'